FILE_TYPE = ["sqmass", "meryldb", "top", "sif", "flowscore", "colab.tar.gz", "pepxml.tsv", "mothur.quan", "cns", "hexrd.yml",
             "source.rs", "phyloseq", "mp3", "tpr", "gii", "fastk_prof", "phyloxml", "intermine_tabular", "plybinary",
             "gatk_interval", "xtc", "cml", "idpdb", "pretext", "ctl.result", "nhx", "netcdf", "embl", "inchi", "pqp",
             "mothur.cons.taxonomy", "malist", "mothur.rabund", "mrc", "gtf", "isa-json", "mothur.design", "mothur.dist",
             "blib", "chrint", "qualsolexa", "bam", "ndx", "gff3.gz", "snptest", "nt", "rdata.sce", "mascotxml", "rdata.xcms.retcor",
             "osw", "fphe", "fastqsolexa.gz", "source.cs", "mztab", "mol2", "gfa2.gz", "pdb", "eland", "maf", "ldindep",
             "mothur.ref.taxonomy", "phar", "inp", "gatk_recal", "itp", "dada2_uniques", "pqr", "source.h", "snpeffdb",
             "neostore.zip", "fsom", "vcf", "metacyto_clr.txt", "arff", "rdata.xcms.raw", "edta", "elandmulti", "mothur.pair.dist",
             "mothur.oligos", "d3_hierarchy", "fastk_hist", "spalndba", "snpmatrix", "rdata.se", "len", "dcd", "rdata.msnbase.raw",
             "mothur.shared", "protobuf2", "sbol", "par", "yaml", "sff", "mothur.align.check", "bigbed", "xvg", "ideaspre", "jsonld",
             "phylip", "fastqcssanger.gz", "flowset", "rma6", "mothur.accnos", "cool", "velvet", "bcf", "cuffdiff.sqlite", "uniprotxml",
             "oxlits", "fastqsolexa", "hdf4", "visium.tar.gz", "gff3", "oxlicg", "hmm2", "ab1", "toml", "extxyz", "interval", "xg",
             "pphe", "fped", "gmsh.geo", "xlsx", "fastqsanger.bz2", "lped", "gatk_dbsnp", "hmm3", "asn1-binary", "nii1", "tandem",
             "bil", "cell", "spec.xml", "sbml", "vtkbinary", "mothur.lower.dist", "bed12", "mothur.groups", "nex", "prj", "cpt",
             "4dn_pairsam", "mothur.tax.summary", "xsd", "rdata.camera.positive", "splib_noindex", "storm.check", "psl", "bgzip", "flv",
             "nii1.gz", "qzv", "genbank.gz", "cel", "mothur.count_table", "mothur.otu.corr", "cxb", "protxml.tsv", "ome.tiff",
             "mothur.otulabels", "fast5.tar.bz2", "maskinfo-asn1", "protxml", "neper.tesr", "vel", "storm.sample", "kallisto.idx",
             "pithya.model", "rds", "gmsh.msh", "plyascii", "biom1", "deeptools_coverage_matrix", "hep.root", "flowstat1", "mol", "cmap",
             "wiff", "neper.points.tsv", "fps", "bed", "mzqc", "mcool", "ffdata", "mgf", "mztab2", "maskinfo-asn1-binary", "fasta",
             "augustus", "gafa.sqlite", "qza", "wiff2", "trackhub", "scool", "obfs", "stl", "cps", "snpsiftdbnsfp", "icm", "bed6", "agp",
             "fast5.tar.gz", "genenotebook", "npy", "param", "sf3", "grd", "idat", "mothur.map", "gff", "parquet", "bcf_uncompressed",
             "hexrd.materials.h5", "fastq.gz", "fastqillumina.bz2", "idxml", "source.cpp", "wiff.tar", "magres", "mothur.list", "oxlist",
             "nmrml", "pssm-asn1", "wav", "fastk_ktab", "sdf", "pithya.property", "h5mlm", "dbn", "vcf_bgzip", "agilentbrukeryep.d.tar",
             "flowstat3", "mothur.otu", "flowmfi", "gfa2", "traml", "cisml", "genbank", "mpg", "pdbqt", "newick", "fast5.tar", "star",
             "shp", "castep", "rdata.camera.quick", "cnn", "txt", "xgmml", "gff_tabix.gz", "mzdata", "ampvis2", "gff3.bz2",
             "fastqillumina.gz", "pbed", "xml", "smat", "scf", "paramxml", "neper.points", "taxonomy", "dta", "dada2_sequencetable",
             "hdt", "xyz", "ffindex", "msp", "probed", "axt", "scidx", "paf", "kroenik", "fastqillumina", "flowtext", "chain", "excel.xls",
             "hexrd.eta_ome.npz", "prmtop", "protobuf3", "bref3", "tar", "fcs", "bcsl.model", "onnx", "tsv", "bedstrict", "rdf", "source.c",
             "chira.sqlite", "bigwig", "a3m", "fits", "hexrd.accepted_orientations", "ms2", "fastqcssanger.bz2", "analyze75", "mz.sqlite",
             "mrm", "qual454", "drf", "imgt.json", "csv", "colab.tar", "postgresql", "psms", "grd.tgz", "fqtoc", "mzid", "rdata",
             "mothur.align", "tck", "nii2.gz", "memepsp", "bcsl.ts", "brukertdf.d.tar", "dlib", "wiff2.tar", "flowframe", "mp4", "biom2",
             "trr", "auto", "edr", "mothur.masked.quan", "json", "rdata.xcms.findchrompeaks", "mothur.axes", "mothur.freq", "sam", "sra",
             "xmfa", "mothur.seq.taxonomy", "mothur.sabund", "spalndbnp", "mothur.sff.flow", "lav", "gemini.sqlite", "mtx", "vg", "owl",
             "brukerbaf.d.tar", "twobit", "neper.mscell", "msh", "mkv", "pepxml", "rdata.camera.negative", "daa", "imzml", "mzml", "grib",
             "source.go", "blastxml", "qname_sorted.bam", "gal", "obo", "rdata.xcms.group", "mothur.filter", "thermo.raw", "fast5.tar.xz",
             "fastq", "snaphmm", "neper.tess", "n3", "metacyto_summary.txt", "trafoxml", "fasta.gz", "hdr", "bed_tabix.gz", "probam", "asn1",
             "loom", "expression.json", "agilentmasshunter.d.tar", "npz", "juicer_medium_tabix.gz", "tiff", "mzq", "sqlite", "gii.gz", "hlf",
             "peplist", "jp2", "tabular", "ipynb", "oxligl", "dada2_dada", "mothur.summary", "wig", "picard_interval_list", "sra_manifest.tabular",
             "vtkascii", "4dn_pairs", "metacyto_stats.txt", "mothur.filtered.masked.quan", "trk", "jellyfish", "paf.gz", "gatk_report",
             "mothur.names", "flowclr", "affybatch", "mothur.align.report", "csfasta", "fastqsanger.gz", "bus", "pileup", "qcml",
             "dada2_mergepairs", "dzi", "unsorted.bam", "hexrd.images.npz", "tgz", "isa-tab", "h5ad", "pithya.result", "qualillumina", "mdp",
             "mothur.filtered.quan", "stockholm", "gpr", "oxling", "gro", "inpcrd", "ptkscmp", "splib", "fastq.bz2", "consensusxml", "peff",
             "ncbi_genome_dataset.zip", "eset", "rdata.xcms.fillpeaks", "smi", "ludwig_model", "nii2", "h5", "ttl", "mzxml", "cnr", "cram", "ct",
             "dbnsfp.tabular", "fastqsanger", "mothur.relabund", "peptideshaker_archive", "memexml", "fai", "png", "qiime2.tabular", "mothur.tre",
             "odgi", "den_fmt", "fastqsolexa.bz2", "pdf", "rna_eps", "rdock_as", "encodepeak", "zset.geof", "source.py", "fastqcssanger", "elib",
             "watersmasslynx.raw.tar", "mothur.square.dist", "hexrd.scored_orientations.npz", "textgrid", "cif", "ckpt", "fastg", "mongodb",
             "xquest.xml", "dta2d", "qualsolid", "searchgui_archive", "tabular.gz", "mz5", "bedgraph", "gfa1.gz", "gfa1", "flowstat2", "pov",
             "featurexml", "dada2_errorrates", "oxliss", "geojson", "mothur.rdp.taxonomy", "deeptools_compute_matrix_archive", "gatk_tranche",
             "ncbitaxonomy.sqlite", "zip", "hhr"]
