name: biobb_370
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_amber==3.7.1
  - biobb_analysis==3.7.0
  - biobb_chemistry==3.7.0
  - biobb_dna==3.7.0
  - biobb_io==3.7.0
  - biobb_md==3.7.0
  - biobb_ml==3.7.0
  - biobb_model==3.7.0
  - biobb_pmx==3.7.0
  - biobb_structure_utils==3.7.0
  - biobb_vs==3.7.0
  - conda