name: biobb_370
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_amber==3.7.1
  - biobb_analysis==3.7.0
  - biobb_chemistry==3.7.0
  - biobb_dna==3.7.1
  - biobb_io==3.7.0
  - biobb_md==3.7.0
  - biobb_ml==3.7.0
  - biobb_model==3.7.0
  - biobb_pmx==3.7.0
  - biobb_structure_utils==3.7.1
  - biobb_vs==3.7.0
  - conda

# EXTRA STEPS

# MODELLER KEY
# conda install -c salilab modeller

# MODELLER KEY
# There's two ways of registering the Modeller Key:
#         A. Through the config.py file:
#            A.1. Edit:
#                     [PATH_TO_CONDA_ENV]/lib/modeller-10.1/modlib/modeller/config.py
#            A.2. Add line:
#                     license = r'MY_MODELLER_KEY'
#         B. Through the env variable KEY_MODELLER:
#            B.1. Edit:
#                     [PATH_TO_CONDA_ENV]/lib/modeller-10.1/modlib/modeller/config.py
#            B.2. Comment line:
#                     license = r'MY_MODELLER_KEY'
#            B.3. Set the KEY_MODELLER env var:
#                     export KEY_MODELLER="MY_MODELLER_KEY"



# CURVES
# locate .curvesplus folder in your environment folder