name: biobb_420
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - biobb_adapters
  - biobb_amber==4.2.0
  - biobb_analysis==4.2.0
  - biobb_chemistry==4.2.1
  - biobb_cmip==4.2.0
  - biobb_cp2k==4.2.0
  - biobb_dna==4.2.4
  - biobb_flexdyn==4.2.0
  - biobb_flexserv==4.2.0
  - biobb_godmd==4.2.0
  - biobb_gromacs==4.2.0
  - biobb_haddock
  - biobb_io==4.2.0
  - biobb_model==4.2.3
  - biobb_pdb_tools==4.2.0
  - biobb_pmx==4.2.1
  - biobb_pytorch==4.2.0
  - biobb_structure_utils==4.2.0
  - biobb_vs==4.2.0
  - modeller
  - conda
  #
  #- biobb_haddock==4.2.0

# EXTRA STEPS

# MODELLER KEY
# conda install -c salilab modeller

# MODELLER KEY
# There's two ways of registering the Modeller Key:
#         A. Through the config.py file:
#            A.1. Edit:
#                     [PATH_TO_CONDA_ENV]/lib/modeller-10.1/modlib/modeller/config.py
#            A.2. Add line:
#                     license = r'MY_MODELLER_KEY'
#         B. Through the env variable KEY_MODELLER:
#            B.1. Edit:
#                     [PATH_TO_CONDA_ENV]/lib/modeller-10.1/modlib/modeller/config.py
#            B.2. Comment line:
#                     license = r'MY_MODELLER_KEY'
#            B.3. Set the KEY_MODELLER env var:
#                     export KEY_MODELLER="MY_MODELLER_KEY"



# CURVES
# locate .curvesplus folder in your environment folder
